In [70]:
import os
os.environ["TF_CPP_MIN_LOG_LEVEL"] = "0"  # Enable verbose logs
print("Starting TensorFlow import...")
import tensorflow as tf
print("TensorFlow imported successfully.")

Starting TensorFlow import...
TensorFlow imported successfully.


### Simple Constants

Let's show how to create a simple constant with Tensorflow, which TF stores as a tensor object:

In [71]:
hello = tf.constant('Hello World')

In [72]:
type(hello)

tensorflow.python.framework.ops.EagerTensor

In [73]:
x = tf.constant(100)

In [74]:
type(x)

tensorflow.python.framework.ops.EagerTensor

### Running Sessions

Now you can create a TensorFlow Session, which is a class for running TensorFlow operations.

A `Session` object encapsulates the environment in which `Operation`
objects are executed, and `Tensor` objects are evaluated. For example:

In [75]:
a = tf.constant(5)
b = tf.constant(3)
c = a + b

print(c)

tf.Tensor(8, shape=(), dtype=int32)


## Operations

You can line up multiple Tensorflow operations in to be run during a session:

In [76]:
x = tf.constant(2)
y = tf.constant(3)

print(x+y)

tf.Tensor(5, shape=(), dtype=int32)


In [77]:
    print('Operations with Constants')
    print('Addition',x+y)
    print('Subtraction',x-y)
    print('Multiplication',x*y)
    print('Division',x/y)

Operations with Constants
Addition tf.Tensor(5, shape=(), dtype=int32)
Subtraction tf.Tensor(-1, shape=(), dtype=int32)
Multiplication tf.Tensor(6, shape=(), dtype=int32)
Division tf.Tensor(0.6666666666666666, shape=(), dtype=float64)


### Placeholder

You may not always have the constants right away, and you may be waiting for a constant to appear after a cycle of operations. **tf.placeholder** is a tool for this. It inserts a placeholder for a tensor that will be always fed.

**Important**: This tensor will produce an error if evaluated. Its value must be fed using the `feed_dict` optional argument to `Session.run()`,
`Tensor.eval()`, or `Operation.run()`. For example, for a placeholder of a matrix of floating point numbers:

    x = tf.placeholder(tf.float32, shape=(1024, 1024))

Here is an example for integer placeholders:

In [78]:
type(x)

tensorflow.python.framework.ops.EagerTensor

### Defining Operations

In [79]:
add = tf.add(x,y)
sub = tf.subtract(x,y)
mul = tf.multiply(x,y)

Running operations with variable input:

In [80]:
d = {x:20,y:30}

TypeError: Tensor is unhashable. Instead, use tensor.ref() as the key.

In [ ]:
with tf.Session() as sess:
    print('Operations with Constants')
    print('Addition',sess.run(add,feed_dict=d))
    print('Subtraction',sess.run(sub,feed_dict=d))
    print('Multiplication',sess.run(mul,feed_dict=d))

Operations with Constants
Addition 50
Subtraction -10
Multiplication 600


Now let's see an example of a more complex operation, using Matrix Multiplication. First we need to create the matrices:

In [ ]:
import numpy as np
# Make sure to use floats here, int64 will cause an error.
a = np.array([[5.0,5.0]])
b = np.array([[2.0],[2.0]])

In [ ]:
a

array([[5., 5.]])

In [ ]:
a.shape

(1, 2)

In [ ]:
b

array([[2.],
       [2.]])

In [ ]:
b.shape

(2, 1)

The matrix multiplication operation:

In [82]:

mat1 = tf.constant([[1, 2], [3, 4]])  # Shape: (2,2)
mat2 = tf.constant([[5], [6]])        # Shape: (2,1)

# Perform matrix multiplication
matrix_multi = tf.matmul(mat1, mat2)

# Print the result
print(matrix_multi.numpy())

[[17]
 [39]]


Now run the session to perform the Operation:

In [84]:
result = matrix_multi
print(result)

tf.Tensor(
[[17]
 [39]], shape=(2, 1), dtype=int32)
